"""Your migration message

Revision ID: 91efb581121d
Revises: 
Create Date: 2023-06-16 20:20:12.796038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91efb581121d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('privacy',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('public', 'friends only'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('privacy',
               existing_type=sa.Enum('public', 'friends only'),
               type_=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
